--!strict
-- @Core: Manifest (Single Source of Truth)
-- Identitas & Versi Framework
return {
    Identity = {
        Name = "OVHL Framework",
        Namespace = "omniverse"
    },
    
    Version = {
        Major = 0,
        Minor = 1,
        Patch = 0,
        Full = "0.1.0"
    },
    
    Metadata = {
        BuildType = "Alpha", -- Development / Staging / Production
        LastUpdated = "2025-11-22"
    }
}
