import fs from 'fs-extra';
import { IAuditContext, IAuditIssue } from '../Types/AuditResult.js';
import { GitService } from '../Services/GitService.js';
import { RojoService } from '../Services/RojoService.js';

export class MarkdownAI {
    generate(ctx: IAuditContext): string {
        const date = new Date(ctx.timestamp).toLocaleString();
        const layout = ctx.config.reporting.layout || [];
        
        const git = new GitService(ctx.rootPath);
        const gitInfo = git.getShortInfo();
        const aiCtx = ctx.config.aiContext || {};

        let output = `---
type: project-snapshot
purpose: AI Analysis & Debugging Context
generated_by: OVHL CLI v0.1.0
date: ${date}
---

# 🧠 OVHL ENTERPRISE FRAMEWORK CONTEXT

> **🛑 CRITICAL INSTRUCTION FOR AI AGENT:**
> You are operating within the **OVHL Enterprise Framework**.
> Deviating from the architecture rules below is **STRICTLY FORBIDDEN**.

### 1. 🏛️ ARCHITECTURE LAWS
**Lifecycle:** \`${aiCtx.lifecycle}\`

**Mandatory Rules:**
${aiCtx.architecture ? aiCtx.architecture.map((r:string) => `- ${r}`).join('\n') : ''}

### 2. 🧪 TESTING MANDATE
${aiCtx.testing}

---
# 📊 SNAPSHOT SUMMARY
| Metric | Details |
|---|---|
| **Health Score** | ${ctx.globalScore} / 100 |
| **Target Root** | \`${ctx.rootPath}\` |
| **Git Info** | ${gitInfo} |
| **Analysis Time** | ${ctx.metadata?.duration || 'N/A'} |
---
`;

        for (const sectionId of layout) {
            const section = ctx.results.get(sectionId);
            if (!section) continue;

            output += `\n## ${section.title}\n\n`;
            
            if (section.issues.length > 0) {
                const grouped = this.groupIssues(section.issues);
                
                for (const [title, group] of Object.entries(grouped)) {
                    const first = group[0];
                    const icon = first.type === 'CRITICAL' ? '🔴' : (first.type === 'WARNING' ? '⚠️' : 'ℹ️');
                    
                    output += `### ${icon} ${title} (-${first.penalty} pts)\n`;
                    output += `> **AI Advice:** ${first.message}\n\n`;
                    
                    output += '| File | Line | Code Snippet |\n';
                    output += '|---|---|---|\n';
                    
                    for (const issue of group) {
                        const snippet = issue.snippet ? `\`\`\`${issue.snippet}\`\`\`` : '-';
                        output += `| \`${issue.file}\` | ${issue.line || '-'} | ${snippet} |\n`;
                    }
                    output += '\n';
                }
            }
            output += section.content + '\n';
        }

        // FOOTER: REAL TABLE FROM ROJO (FIXED ESCAPING)
        output += `
---
## 🎯 AI QUICK REFERENCE

### 📂 Rojo Architecture Mapping (Active Configuration)
> This is the **EXACT** mapping from \`default.project.json\`. 
> AI Agents MUST use these virtual paths when suggesting \`require()\` calls.

${ctx.metadata?.rojoMapping || "No Mapping Loaded"}

---
*Generated by OVHL Tools | Enterprise Edition*
`;
        return output;
    }

    private groupIssues(issues: IAuditIssue[]) {
        const grouped: Record<string, IAuditIssue[]> = {};
        for (const i of issues) {
            if (!grouped[i.title]) grouped[i.title] = [];
            grouped[i.title].push(i);
        }
        return grouped;
    }

    save(ctx: IAuditContext, fullPath: string) {
        fs.writeFileSync(fullPath, this.generate(ctx));
    }
}