--!strict
local Assets = {}
Assets.Icons = {
    Navigation = { Home="rbxassetid://11422144365", Inventory="rbxassetid://11422146972", Settings="rbxassetid://11422153282", Shop="rbxassetid://11422151614" },
    Action = { Close="rbxassetid://11293981586", Search="rbxassetid://11293977610", Edit="rbxassetid://11422142491", Delete="rbxassetid://11422154215" },
    Status = { Success="rbxassetid://11419717088", Warning="rbxassetid://11419713636", Error="rbxassetid://11419709235" }
}
return table.freeze(Assets)
