#!/bin/bash

echo "⚖️  FIXING HEADER SIZE CALCULATION..."
echo "   Target: Make Total Size respect 'SCAN_DIRS' config dynamically."

cat << 'EOF' > lib/reporter.sh
#!/bin/bash

write_header() {
    local file=$1
    
    local git_info=$(get_git_info "$TARGET_ROOT")
    local date_now=$(date '+%Y-%m-%d %H:%M:%S')
    
    local structure_stats=$(get_structure_summary "$TARGET_ROOT")
    local distribution_stats=$(get_file_distribution "$TARGET_ROOT")
    
    # [FIX] Dynamic Size Calculation based on SCAN_DIRS
    local du_args=()
    for dir in "${SCAN_DIRS[@]}"; do
        if [ -d "$TARGET_ROOT/$dir" ]; then
            du_args+=("$TARGET_ROOT/$dir")
        fi
    done

    # Calculate Size (exclude packages/git/node_modules)
    # Jika du_args kosong (tidak ada folder valid), set size ke 0
    if [ ${#du_args[@]} -eq 0 ]; then
        local total_size="0B"
    else
        local total_size=$(du -shc --exclude="Packages" --exclude="_Index" --exclude=".git" --exclude="node_modules" "${du_args[@]}" 2>/dev/null | tail -1 | cut -f1)
    fi

    # Print Header with Markdown Newlines
    cat << YAML_HEADER > "$file"
---
type: project-snapshot  
purpose: AI Analysis & Debugging Context
generated_by: OVHL Audit Tool v3.6 (Dynamic Metrics)
---

# 🧠 OVHL FRAMEWORK INTERNALS (AI-TO-AI CONTEXT)

> **ATTENTION AI AGENT:** Read this architecture summary BEFORE analyzing the code.

### 1. Architecture Philosophy
- **Singleton Service Pattern:** All logic resides in Services (Server) or Controllers (Client).
- **Lifecycle:** \`Init(ctx)\` [Setup Phase] -> \`Start()\` [Runtime Phase].
- **Rule:** Never execute runtime logic (loops, events) in \`Init\`. Use \`Start\`.

### 2. Core Systems
- **Loader:** Uses \`Proxy\` metatables. \`Loader.Pkg("Name")\` fuzzy matches folders in \`Packages\`.
- **Bridge:** Networking Layer. Enforces \`SharedConfig\` contracts (Args type, Rate Limit).
- **Context:** Dependency Injection container passed to \`Init\`. Use \`ctx:CreateLogger("DOMAIN")\`.

---

# 📊 Project Snapshot

**Generated:** $date_now  
**Target Directories:** \`${SCAN_DIRS[*]}\`  
**Git Info:** $git_info  
**Structure:** $structure_stats  
**File Distribution:** $distribution_stats  
**Total Size:** $total_size  

---

YAML_HEADER
}

write_footer() {
    local file=$1
    cat << 'FOOTER_TEXT' >> "$file"

---

## 🎯 AI Quick Reference

### Common Analysis Tasks:

1. **🐛 Debug Error**
   - Locate the error message in the relevant file (use line numbers!)
   - Check surrounding context and dependencies  
   - Suggest fixes with specific line numbers

2. **📝 Code Review**
   - Check for best practices and patterns
   - Identify potential bugs or improvements
   - Suggest refactoring opportunities

3. **🗂️ Architecture Analysis**
   - Review module organization  
   - Check separation of concerns (client/server/shared)
   - Validate dependency graphs and race conditions

4. **📚 Documentation**
   - Identify undocumented functions
   - Suggest comments for complex logic
   - Generate API documentation

### File Organization:
- **src/StarterPlayer/StarterPlayerScripts/OVHL/**: Client-side code (runs on player's game client)
- **src/ServerScriptService/OVHL/**: Server-side code (runs on game server)  
- **src/ReplicatedStorage/OVHL/**: Shared code (accessible by both client and server)
- **tests/**: Test files for automated testing

---

*Generated by OVHL Framework ULTIMATE Audit Tool v3*
FOOTER_TEXT
}

write_section() {
    echo -e "\n## $2\n" >> "$1"
}
EOF

echo "✅ Header fixed to support dynamic SCAN_DIRS array."
EOF