--!strict
-- @Asset: Icon Registry (Updated)
return table.freeze({
    Icons = {
        -- [FIX] Ganti ID Close ke yang lebih modern/HD (Lucide Style X)
        Close = "rbxassetid://11293981586", 
        Loading = "rbxassetid://16960657067", 
    },
    Placeholders = {
        Sword = "rbxassetid://13006407439", 
        Potion = "rbxassetid://12905487363",
        Generic = "rbxassetid://12663335633" 
    }
})
